language: python
env:
  - CODECLIMATE_REPO_TOKEN=35f36cc29515cff2bca7c202b12a906d7154e8d104fba662fe8f6ce209518db5
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

# command to install dependencies
install: "pip install -r requirements-dev.txt"
# command to run tests
script:
  - pip freeze
  - nosetests --with-coverage --cover-inclusive --cover-package=sqlalchemy_mixins
  - export PYTHONPATH=.:$PYTHONPATH
  - python examples/activerecord.py
  - python examples/all_features.py
  - python examples/eagerload.py
  - python examples/repr.py
  - python examples/smartquery.py
  - python examples/serialize.py
after_success:
  - codeclimate-test-reporter
